# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  networking.hostName = "plusgut-dell";

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-89c823b3-af2a-4be8-82b5-8e80aa0effdc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-89c823b3-af2a-4be8-82b5-8e80aa0effdc".device = "/dev/disk/by-uuid/89c823b3-af2a-4be8-82b5-8e80aa0effdc";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/51B8-6998";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-bb3b83b9-8c15-4f4f-9d9e-5c8ba7ab0c2e"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
