theme = "nord"

[editor]
cursorline = true
auto-save = true
bufferline = "always"
color-modes = true
auto-pairs = false

[editor.whitespace]
render = "all"

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[keys.normal]
right = "shrink_selection"
left = "expand_selection"
down = "select_next_sibling"
up = "select_prev_sibling"
