theme = "nord"

[editor]
auto-save = true
bufferline = "always"

[editor.lsp]
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true

[keys.normal]
right = "shrink_selection"
left = "expand_selection"
down = "select_next_sibling"
up = "select_prev_sibling"