[[language]]
name = "javascript"

[[language]]
name = "strictly"
scope = "source.strictly"
file-types = ["sly"]
comment-token = "//"
indent = { tab-width = 2, unit = "\t" }
roots = []

[[grammar]]
name = "strictly"
source = { path = "/home/plusgut/projects/strictly/packages/tree-sitter-strictly/result" }
